[package]
name = "tvg-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rmp-serde = "1.1"
tvg = { path = "../../tvg", features = ["serde"] }
wasm-bindgen = "0.2"
